image: Visual Studio 2022

# Add this to your YML file
install:
 - cinst opencover.portable
 - cinst codecov

test: off

before_build:
 - nuget restore
 
test_script:
 - ps: ./coverage.ps1

after_test:
 - codecov -f coverage.xml
